#!/usr/bin/env bash

# Easier navigation: .., ..., ...., ....., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~" # `cd` is probably faster to type though
alias -- --="cd -"

# git
alias g="git"
alias ga="git add"
alias gb="git branch"
alias gbl="git branch --list"
alias name="git symbolic-ref HEAD 2>/dev/null --short" # Get the current branch name
alias gc="git commit"
alias amend="git commit --amend"
alias aamend="git commit -a --amend"
alias co="git checkout"
alias gd="git diff"
alias gr="git reset"
alias reset="git reset"
alias hard="git reset --hard" # completely get rid of one or more commits
alias gs="git status"
alias show="git show"
alias sno="git show --name-only"
alias stash="git stash"
alias apply="git stash apply"
alias list="git stash list"
alias undo="git reset HEAD@{1} --soft" # Undo the last action
alias h="HEAD"
alias grh="git reset HEAD"
alias r="git rebase"
alias rebase="git fetch && r master" # This will update the tree and play your commits over it
alias r5="r -i HEAD~5"
alias r10="r -i HEAD~10"
alias ri="r -i master"
alias rc="r --continue"
alias cont="r --continue"

alias land="merge_and_delete_branch"
alias pull="git pull origin master" # This will merge master into any current commits
alias ship="git push origin master"
alias ol="git log --pretty=oneline --decorate"
alias oldates="git log --pretty=format:'%h %ai %an %s'"
alias mine="git log --author=egiovanola --date=short --pretty=format:'%h %ad %s'"
alias exportmine="git log --author=egiovanola --date=short --pretty=format:'%h,%ad,%s' > git-log.csv"

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'
